name: Build
on:
  pull_request:
  push:
    branches: [ main, local, test/gha ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      -
        name: Check out repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      -
        name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          cache: true
          check-latest: true
          go-version-file: 'go.mod'
      -
        name: Downnlaod Go modules
        run: go mod download -json
      -
        name: Install golint
        run: go install golang.org/x/lint/golint@latest
      -
        name: Check formatting
        run: gofmt -d -e -l -s .
      -
        name: Lint
        run: golint -set_exit_status ./...
      -
        name: Build and test
        run: |
          go test -v ./...
          go build ./cmd/walker
          go build ./cmd/reporter

  checks:
    name: Static Checks
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    -
      name: Checkout repo
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
    -
      name: Setup Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        cache: true
        check-latest: true
        go-version-file: 'go.mod'
    -
      id: govulncheck
      name: govulncheck
      uses: golang/govulncheck-action@dd0578b371c987f96d1185abb54344b44352bd58 # v1.0.3
      with:
        cache: false
        go-version-file: 'go.mod'
        repo-checkout: false
    -
      name: Build
      run: go build ./...
    -
      name: staticcheck
      uses: dominikh/staticcheck-action@fe1dd0c3658873b46f8c9bb3291096a617310ca6 # v1.3.1
      continue-on-error: true
      with:
        version: "2023.1.6"
        install-go: false
    -
      name: golangci-lint
      uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # v6.1.1
      with:
        version: v1.55
        # skip-cache: true
        skip-pkg-cache: true
        skip-build-cache: true
