name: Build
on:
  pull_request:
  push:
    branches: [ main, local, test/gha ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    -
      uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
      with:
        egress-policy: audit
    -
      name: Check out repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    -
      name: Setup Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      with:
        cache: true
        check-latest: true
        go-version-file: 'go.mod'
    -
      name: Downnlaod Go modules
      run: go mod download -json
    -
      name: Install golint
      run: go install golang.org/x/lint/golint@latest
    -
      name: Check formatting
      run: gofmt -d -e -l -s .
    -
      name: Lint
      run: golint -set_exit_status ./...
    -
      name: Build and test
      run: |
        go test -v ./...
        go build ./cmd/walker
        go build ./cmd/reporter

  checks:
    name: Static Checks
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    -
      uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
      with:
        egress-policy: audit
    -
      name: Checkout repo
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    -
      name: Setup Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      with:
        cache: true
        check-latest: true
        go-version-file: 'go.mod'
    -
      id: govulncheck
      name: govulncheck
      uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
      with:
        cache: false
        #go-version-file: 'go.mod'
        # An explicit Go version is needed for govulncheck-action since internally
        # it uses an outdated setup-go@v5.0 action that does not respect the 'toolchain'
        # directive in the 'go.mod' file.
        go-version-input: '1.25.8'
        repo-checkout: false
    -
      name: Build
      run: go build ./...
    -
      name: staticcheck
      uses: dominikh/staticcheck-action@9716614d4101e79b4340dd97b10e54d68234e431 # v1.4.1
      continue-on-error: true
      with:
        version: "2025.1.1"
        install-go: false
        use-cache: false
    -
      name: golangci-lint
      uses: golangci/golangci-lint-action@e7fa5ac41e1cf5b7d48e45e42232ce7ada589601 # v9.1.0
      with:
        version: v2.6.1
        # Use a long invalidation interval, the go.mod hash is more likely to
        # change more frequently and force a cache invalidation anyway.
        cache-invalidation-interval: 60
        #skip-cache: true
        #skip-save-cache: true
