name: Build
on:
  pull_request:
  push:
    branches: [ main, local, test/gha ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      -
        name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      -
        name: Setup Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          cache: true
          check-latest: true
          go-version-file: 'go.mod'
      -
        name: Downnlaod Go modules
        run: go mod download -json
      -
        name: Install golint
        run: go install golang.org/x/lint/golint@latest
      -
        name: Check formatting
        run: gofmt -d -e -l -s .
      -
        name: Lint
        run: golint -set_exit_status ./...
      -
        name: Build and test
        run: |
          go test -v ./...
          go build ./cmd/walker
          go build ./cmd/reporter

  checks:
    name: Static Checks
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    -
      name: Checkout repo
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    -
      name: Setup Go
      uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
      with:
        cache: true
        check-latest: true
        go-version-file: 'go.mod'
    -
      id: govulncheck
      name: govulncheck
      uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
      with:
        cache: false
        go-version-file: 'go.mod'
        go-version-input:
        repo-checkout: false
    -
      name: Build
      run: go build ./...
    -
      name: staticcheck
      uses: dominikh/staticcheck-action@fe1dd0c3658873b46f8c9bb3291096a617310ca6 # v1.3.1
      continue-on-error: true
      with:
        version: "2024.1.1"
        install-go: false
    -
      name: golangci-lint
      uses: golangci/golangci-lint-action@2e788936b09dd82dc280e845628a40d2ba6b204c # v6.3.1
      with:
        version: v1.61.0
        # skip-cache: true
        # skip-save-cache: true
