name: Test
on: [push, pull_request]

permissions:
  contents: read

jobs:
  make-test:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: 'stable'

      - name: Run Go unit tests
        run: go test ./...
